### PR TITLE
Enable SSL connections

### PR DESCRIPTION
**Pull request by KasperSkytte**
Was having an issue with SSL connections through curl+httr from R. All I needed was to install ca-certificates in the image

### CODE REVIEW

**Comment by KasperSkytte** [comment]
Same problem as [this](https://stackoverflow.com/questions/53636902/error-in-curl-ssl-certificate-problem-unable-to-get-local-issuer-certificate)

**Comment by hvalev** [comment]
Thank you @KasperSkytte for this PR. I'll merge this request and overwrite the docker images on docker hub for the current version.

**Comment by KasperSkytte** [comment]
Thanks. And nice image!

I was also about to add `RUN mkdir -p ~/.R && echo "MAKEFLAGS = -j4" > ~/.R/Makevars` to speed up compilation of R packages, both when building the image and for R itself when it's run through the container. But then, crash. Apparantly 4GB wasn't enough for running the final line: https://github.com/hvalev/shiny-server-arm-docker/blob/b9089a142f7c4a08b175bf63764faac4a7741c22/Dockerfile#L98

**Comment by hvalev** [comment]
Thanks and this is a good idea, particularly for github actions as I believe the build instances have more than 4GB. I'll need to test it on a separate branch when I have a little bit more time. Note to self: I would also need to update the 'build-it-yourself' part of the documentation.

**Pull request merged**
